### ISSUE TITLE
Zog Barking

### ISSUE THREAD

**Issue by cihapus** [danzen/zimjs#11]
playing with Zim soundwave and my console's getting flooded, even with zon=false,

line 18425 missing a zon check -
zog(dataArray)
should read?
if (zon) zog(dataArray);

Enjoying the library, videos, docs etc - thanks for all your hard work.

**Comment by danzen** [comment]
Oh ya - sorry about that.  No... the zog() should not have been left there.  We noticed it too and it was removed in the subsequent release.  Thanks for pointing it out.  All the best.
