### ISSUE TITLE
Dial limit:False property not working with arrow keys

### ISSUE THREAD

**Issue by Rmnlly** [danzen/zimjs#24]
When using a dial and setting the limit property to false we are unable to use the arrow keys to make the dial go past the maximum value. 

Using ZimJS 6.6.3 for this example. 

Example dial code:
`let horDial = new Dial({
          width: 65,
          limit: false,
          useTicks: false,
          indicatorType: "dot",
          indicatorScale: .75,
          color: "#fff"
        })`

**Comment by Rmnlly** [comment]
The arrow keys work if we use relative:true as a parameter of the dial however.

**Comment by Rmnlly** [comment]
If we use relative:true but also had a relativeMin and relativeMax then the arrow keys are unable to continue spinning the dial once we hit one of those values.

**Comment by danzen** [comment]
Thanks - ZIM 6.6.4 has fixed this.  In ZIM 6.7.0 relative was renamed to continuous for better clarity.
