### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by Manthan224** [danzen/zimjs#26]

**Comment by danzen** [comment]
Hi Manthan244 - we are working on it. I come from a Flash background so used types there but have not used TypeScript.  So... TypeScript is now installed on Atom, I am going through the tutorials, etc.  We have another here who uses TypeScript and is helping.  We also have another working on getting ZIM on NPM.  So... looking forward to it - let's hope we can get something there within a month.

**Comment by Manthan224** [comment]
[index.d.ts.zip](https://github.com/danzen/zimjs/files/1726773/index.d.ts.zip)
Sounds great.
I have created temporary typings(only root level) if anyone needs. 
I will move on to original once it is available.

**Comment by danzen** [comment]
Thanks Manthan224! Just an update - all is going well with the TypeScript Typings  -  over 1000 lines so far.  Will be way more once I parse all the things that get duplicated. I am on the last few controls and then the Frame and the Meta - should finish that tomorrow and then have to code the parser.

**Comment by danzen** [comment]
A complete set of typings is available here: http://zimjs.com/typescript/zim_ts.zip.  We will try them out for a while and then we can submit to the typings github.  Please let me know if we did anything in an awkward manner, etc.  This was our first go at TypeScript.  We will keep this issue open as there are bound to be some further issues.

**Comment by danzen** [comment]
We have now updated our npm to be more robust https://www.npmjs.com/package/zimjs with typings too.
