### ISSUE TITLE
Label.labelWidth change issue.

### ISSUE THREAD

**Issue by mojoco** [danzen/zimjs#32]
The size is not updated !
To fix them, I think you need simply call 'setSize()', inside the 'defineProperty'..
I hope this help !

**Comment by danzen** [comment]
var label = new Label("THIS IS A TEST TO SEE IF WRAPPING WORKS").pos(20,20);
label.labelWidth = 100;
I tried this and it worked... did you do a stage.update() afterwards?  We can certainly go in and make updates if we need to - can you show some code perhaps so we can double check things.  Thanks!
