### ISSUE TITLE
In IE11, the Frame can't load all images succeeded in the first time.

### ISSUE THREAD

**Issue by kero13ro** [danzen/zimjs#36]
When checking Cross-browser compatibility, only IE11 doesn't appear all images correctly in the first time. But after refreshing, it appears fine.

**Comment by ssshammi** [comment]
the workaround for this is load the images in DOM. in addition and display:none style

**Comment by kero13ro** [comment]
> the workaround for this is load the images in DOM. in addition and display:none style

Thanks for the reply, but after appending img in HTML, it seems has the same issue, not appearing correctly in the first time.

**Comment by danzen** [comment]
Hey folks - just saw this issue.  @kero13ro we use the CreateJS PreloadJS behind the scene to do preloading.  I just checked the issues there https://github.com/CreateJS/PreloadJS/issues and did not find any IE11 general issues. If you have worked with CreateJS before, you might try a simple example in ZIM and a simple example in CreateJS and see what the results are.  How many images are you loading and how big?  Are you loading through the Frame or through frame.loadAssets().  If you are using the second way, make sure that you have a frame.on("complete", function(){ do rest of code here});  Also, perhaps we could work through this at https://zimjs.com/slack - hope to see you there.

**Comment by ssshammi** [comment]
Ok for me this is when you use spritesheet setting Combine image to spritesheet option,  in publish settings, it does not wait for PreloadJS images. this is a bug in animate cc. 
 
Hope that helps
Thanks and Regards
