### ISSUE TITLE
Refactoring code 

### ISSUE THREAD

**Issue by Mr-Chehata** [danzen/zimjs#38]
this is a powerfull and a rich Canvas Wrapper  we like it and we want help you improve it ..but first 
 it will be more scalable and maintainable library by adding a good code Structure with refactoring the main code and redesign it with sub-module concept (Frame module, Animation Module, Physics module ...) 
thank u Dan for your great effort .

**Comment by danzen** [comment]
Thanks @Mr-Chehata - we did start with modules - as per the sections of the docs.  This was based on the ES5 Module pattern as it was pre-ES6-adoption.  It was found that as a Framework, the modules are less important to the coder - we almost always use all the modules.  The code size issue was solved mostly by ZIM Distill (tree-shaking).  The only minor issue there is caching... modules could be cached but Distilled code can be cached per user per app but not across apps.  

ES6 modules are not going to work well with our users which range from professionals to kids.  We do not want to force a namespace on people and there is no way that we want to slow down developers or kids by making them choose which classes and functions they want to import.

Modules could still come in handy for maintenance - and perhaps for collaboration.  But ZIM is almost complete and as a sole creator, was fine for maintaining and building with a few bookmarks, etc.  

So on the face of it - yes, modules are scaleable and good code structure... but there is a fair bit going on here.  A namespace can be applied if desired by using zns=true before importing ZIM.  Our methods are actually zim functions that can work as functions or methods to handle operating on raw CreateJS objects.  There is the ZIM DUO technique of passing in parameters or a single configuration object with properties that match the parameter names.  There is how distill works to record functions that are used.  There is STYLE applied across DisplayObjects and Controls.  There is a TypeScript parser that creates over 4000 lines of typing.  There is a Docs parser that creates docs from the code.  Many of these are easier with one file.

Of course, we are open to discussion, and help yourself to trying to put ZIM in modules, we would lend guidance if you were to try.  It is something that we have though much about over the last few years - and fairly firmly decided that that we do not want "upgrade" - same with converting all the code to ES6.  There is really no reason that we can see to do this.  We have been moving forward with ES6 in examples - for instance, all the CodePen examples.  And the ZIM Skool has been updated.

Cheers!

**Comment by Mr-Chehata** [comment]
Thank you @danzen for your explanatory Reply ...
I think this convincing  for me , you already  try it and seems that isn't a better techno-architecture for the Zim  philosophy/culture ...
Thanks

**Comment by danzen** [comment]
Thank you for caring @Mr-Chehata - we do not mean to put you off hanging around or using ZIM - and we will continue to assess the situation!

**Comment by danzen** [comment]
Just a note, we have provided ES6 Modules at https://zimjs.com/es6.html#MODULES which wrap the ES5 code with exports.  These are for the main ZIM but also for combinations of the libraries
