### ISSUE TITLE
2 bugs found.

### ISSUE THREAD

**Issue by dnvs** [danzen/zimjs#41]
1,window constructor parameter: scrollBarActive =false, will cause a error bug.
2,custom list item has a background rectangle with amost transparent white  color(maybe "fcfcfc"), it's very hard to see ,but it looks buggy.

**Comment by danzen** [comment]
Hi @dnvs - thanks - these have been patched in ZIM 10.9.0 - and you are mentioned in https://zimjs.com/updates.html !  The color was faint rgba(255,255,255,.01) the lightest color that is interactive.  But there is a createjs hitArea property so we applied that through ZIM expand(0).  And the other was a missed update to a conditional.  Thanks!  (sorry for the delay... we have been extra busy with 10.9.0 data binding launch and testing)

**Comment by dnvs** [comment]
cool～ you are so quick ！
