### ISSUE TITLE
bug report: SVGContainer("xxx.svg") parse error, but bitmap ("xxx.svg") works.

### ISSUE THREAD

**Issue by dnvs** [danzen/zimjs#42]
Uncaught TypeError: Cannot read property 'trim' of undefined
    at zim.js:1596
    at go.loop (zim.js:10731)
    at C (zim.js:1593)
    at L (zim.js:1712)
    at k (zim.js:1730)
    at zim.js:1696
    at Object.go.loop (zim.js:10732)
    at c (zim.js:1694)
    at zim.js:1704
    at Object.go.loop (zim.js:10732)

here is my svg file:

`<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24pt" height="22pt" viewBox="0 0 24 22" version="1.1">
<defs>
<g>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d="M 0.984375 -16.546875 L 19.0625 -16.546875 L 19.0625 -19.09375 L 0.921875 -19.09375 L 0.921875 -16.546875 Z M 0.984375 -12.265625 L 19.0625 -12.265625 L 19.0625 -14.8125 L 0.921875 -14.8125 L 0.921875 -12.265625 Z M 0.984375 -8 L 19.0625 -8 L 19.0625 -10.546875 L 0.921875 -10.546875 L 0.921875 -8 Z M 0.984375 -3.71875 L 19.0625 -3.71875 L 19.0625 -6.265625 L 0.921875 -6.265625 L 0.921875 -3.71875 Z M 0.984375 0.546875 L 19.0625 0.546875 L 19.0625 -2 L 0.921875 -2 L 0.921875 0.546875 Z M 0.984375 4.828125 L 19.0625 4.828125 L 19.0625 2.28125 L 0.921875 2.28125 L 0.921875 4.828125 Z M 0.984375 4.828125 "/>
</symbol>
<symbol overflow="visible" id="glyph0-1">
<path style="stroke:none;" d="M 3 -6.9375 C 3.328125 -6.9375 3.625 -7.09375 3.84375 -7.3125 L 5.0625 -8.421875 L 5.0625 0.28125 C 5.0625 1.734375 5.984375 2.609375 7.46875 2.609375 L 20.21875 2.609375 C 21.71875 2.609375 22.625 1.734375 22.625 0.28125 L 22.625 -8.421875 L 23.84375 -7.3125 C 24.078125 -7.09375 24.375 -6.9375 24.703125 -6.9375 C 25.265625 -6.9375 25.75 -7.328125 25.75 -7.875 C 25.75 -8.203125 25.625 -8.46875 25.375 -8.703125 L 21.84375 -11.921875 L 21.84375 -17.796875 C 21.84375 -18.21875 21.515625 -18.53125 21.078125 -18.53125 L 19.5 -18.53125 C 19.0625 -18.53125 18.71875 -18.21875 18.71875 -17.796875 L 18.71875 -14.78125 L 15.265625 -17.90625 C 14.859375 -18.296875 14.34375 -18.5 13.84375 -18.5 C 13.34375 -18.5 12.828125 -18.296875 12.421875 -17.90625 L 2.328125 -8.703125 C 2.0625 -8.46875 1.9375 -8.203125 1.9375 -7.875 C 1.9375 -7.328125 2.4375 -6.9375 3 -6.9375 Z M 16.734375 -5.796875 C 16.734375 -6.265625 16.40625 -6.578125 15.953125 -6.578125 L 11.765625 -6.578125 C 11.296875 -6.578125 10.953125 -6.265625 10.953125 -5.796875 L 10.953125 0.609375 L 8 0.609375 C 7.390625 0.609375 7.09375 0.296875 7.09375 -0.3125 L 7.09375 -10.28125 L 13.578125 -16.1875 C 13.65625 -16.265625 13.734375 -16.3125 13.84375 -16.3125 C 13.953125 -16.3125 14.03125 -16.28125 14.125 -16.1875 L 20.59375 -10.28125 L 20.59375 -0.3125 C 20.59375 0.296875 20.3125 0.609375 19.703125 0.609375 L 16.734375 0.609375 Z M 16.734375 -5.796875 "/>
</symbol>
</g>
</defs>
<g id="surface1">
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph0-1" x="-1.847656" y="19"/>
</g>
</g>
</svg>
`

**Comment by dnvs** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24pt" height="22pt" viewBox="0 0 24 22" version="1.1">
<defs>
<g>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d="M 0.984375 -16.546875 L 19.0625 -16.546875 L 19.0625 -19.09375 L 0.921875 -19.09375 L 0.921875 -16.546875 Z M 0.984375 -12.265625 L 19.0625 -12.265625 L 19.0625 -14.8125 L 0.921875 -14.8125 L 0.921875 -12.265625 Z M 0.984375 -8 L 19.0625 -8 L 19.0625 -10.546875 L 0.921875 -10.546875 L 0.921875 -8 Z M 0.984375 -3.71875 L 19.0625 -3.71875 L 19.0625 -6.265625 L 0.921875 -6.265625 L 0.921875 -3.71875 Z M 0.984375 0.546875 L 19.0625 0.546875 L 19.0625 -2 L 0.921875 -2 L 0.921875 0.546875 Z M 0.984375 4.828125 L 19.0625 4.828125 L 19.0625 2.28125 L 0.921875 2.28125 L 0.921875 4.828125 Z M 0.984375 4.828125 "/>
</symbol>
<symbol overflow="visible" id="glyph0-1">
<path style="stroke:none;" d="M 3 -6.9375 C 3.328125 -6.9375 3.625 -7.09375 3.84375 -7.3125 L 5.0625 -8.421875 L 5.0625 0.28125 C 5.0625 1.734375 5.984375 2.609375 7.46875 2.609375 L 20.21875 2.609375 C 21.71875 2.609375 22.625 1.734375 22.625 0.28125 L 22.625 -8.421875 L 23.84375 -7.3125 C 24.078125 -7.09375 24.375 -6.9375 24.703125 -6.9375 C 25.265625 -6.9375 25.75 -7.328125 25.75 -7.875 C 25.75 -8.203125 25.625 -8.46875 25.375 -8.703125 L 21.84375 -11.921875 L 21.84375 -17.796875 C 21.84375 -18.21875 21.515625 -18.53125 21.078125 -18.53125 L 19.5 -18.53125 C 19.0625 -18.53125 18.71875 -18.21875 18.71875 -17.796875 L 18.71875 -14.78125 L 15.265625 -17.90625 C 14.859375 -18.296875 14.34375 -18.5 13.84375 -18.5 C 13.34375 -18.5 12.828125 -18.296875 12.421875 -17.90625 L 2.328125 -8.703125 C 2.0625 -8.46875 1.9375 -8.203125 1.9375 -7.875 C 1.9375 -7.328125 2.4375 -6.9375 3 -6.9375 Z M 16.734375 -5.796875 C 16.734375 -6.265625 16.40625 -6.578125 15.953125 -6.578125 L 11.765625 -6.578125 C 11.296875 -6.578125 10.953125 -6.265625 10.953125 -5.796875 L 10.953125 0.609375 L 8 0.609375 C 7.390625 0.609375 7.09375 0.296875 7.09375 -0.3125 L 7.09375 -10.28125 L 13.578125 -16.1875 C 13.65625 -16.265625 13.734375 -16.3125 13.84375 -16.3125 C 13.953125 -16.3125 14.03125 -16.28125 14.125 -16.1875 L 20.59375 -10.28125 L 20.59375 -0.3125 C 20.59375 0.296875 20.3125 0.609375 19.703125 0.609375 L 16.734375 0.609375 Z M 16.734375 -5.796875 "/>
</symbol>
</g>
</defs>
<g id="surface1">
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph0-1" x="-1.847656" y="19"/>
</g>
</g>
</svg>

**Comment by dnvs** [comment]
btw, another question about bitmap color,  is there easy way to modify a tint color of bitmap shape?  or is there a way to modify fillcolor of loaded svg file?

**Comment by danzen** [comment]
Hi @dnvs yes for the tint of a bitmap can be adjusted with createjs filter.  https://www.createjs.com/docs/easeljs/classes/ColorFilter.html  You need to cache() the bimap after - even though it is a bitmap. So that would be what to use as I think you would have modify the svg before sending it to a bitmap to change the fill of the "svg".  If you get the SVG to Blob working then you can change color of the blob dynamically with color or borderColor properties.

For the SVG issue... SVGContainer and with SVG passed into Blob() and Squiggle() as points, it does not accept style parameters.  We just added a test to pull them out rather than give an error.  You could try that at https://zimjs.org/cdn/10.9.1/zim_doc.js or just remove the three or four style parameters in the SVG.  I suspect that other things in there my not translate... not sure - like the overflow and symbols.  We have a fellow called KV who requested SVG in the first place and has helped debug.  You could come in to https://zimjs.com/slack and maybe we could look into more things there.  There is also https://zimjs.com/nio/paths.html where you can make your own Blob and Squiggle points without SVG.

**Comment by danzen** [comment]
Cute!  They are little houses...
