### ISSUE TITLE
using zimjs in angular project

### ISSUE THREAD

**Issue by morweiss** [danzen/zimjs#43]
Hi,
i'm trying ti use zimJS in angular project..
is there any example for it? 
thanks!

**Comment by danzen** [comment]
Hi @morweiss generally the idea is that ZIM can be placed in a div.  Give the div an id and then target the div with new Frame("divID") then ZIM will make the canvas fit in the div.  So if you know how to show a div in Angular or it has some sort of web view component then that will probably work.  There are two TAG examples on this page https://zimjs.com/frame.html that scale in different ways.  We also have people talking about these things on our Slack channel so you are welcome to come in and ask at https://zimjs.com/slack.

**Comment by morweiss** [comment]
Thank you! I placed it in a div with the tagID and it's working great! :)

**Comment by danzen** [comment]
Excellent.  You are still welcome to join us in Slack - it is friendly and free.  We'd love to see what you made when you are done.  Cheers.

**Comment by danzen** [comment]
There is now a repo of templates for Vue, Svelte, React and Angular here https://github.com/yoanhg421/zimjs-templates
