### ISSUE TITLE
Mistake in condition check.

### ISSUE THREAD

**Issue by chu4ng** [danzen/zimjs#45]
I was reading docs and saw strange condition check.
You can look it there: [zim.js](https://raw.githubusercontent.com/danzen/zimjs/master/zim.js) +34567
Same for https://zimjs.org/cdn/nft/00/zim_min.js +17234
```
if (line.lineOrientation == zim.HORIZONTAL || line.lineOrientation == "auto") {
    code
}
if (line.orientation == zim.VERTICAL || line.lineOrientation == "auto") {
    code
}

```
You are using not `lineOrientation`, but `orientation`.

Sorry if there is no mistake, but I don't use slack.

**Comment by danzen** [comment]
Thanks @chu4ng - this is patched in ZIM NFT 01.  Cheers.
