### ISSUE TITLE
Drag make animation weird in ZIMSHIM (adobe animate)

### ISSUE THREAD

**Issue by BibbyChung** [danzen/zimjs#46]
Hi there,

I got a weird situation. I watch this tutorial https://youtu.be/xjAyf3my2Bw and do the same thing. 
all things work well. But I add a new MovieClip and make it move loopy by itself. 
When I drag a ball, the ball move become fast a lot. And when I stop drag, anything works well as before.

I make the [example](https://codepen.io/BibbyChung/pen/dydxNOY) in codepen and here is my adobe animate file [a01.fla.zip](https://github.com/danzen/zimjs/files/8973591/a01.fla.zip)

those I use.
```
<script src="https://zimjs.org/cdn/1.3.4/createjs.js"></script>
<script src="https://zimjs.org/cdn/00/zim_min.js"></script>
```

Thanks

**Comment by danzen** [comment]
Hi Bibby - not sure why the MovieClip animation would increase in speed.  While dragging we are adding a stage.update() on pressmove.  When using ZIM, we add all these to a single Ticker.  If you remove the createjs ticker and add a ZIM one then it solves the problem.

![image](https://user-images.githubusercontent.com/380281/175651483-e90d1abb-dbf5-4ffb-a0f4-c57480d82b09.png)

**Comment by BibbyChung** [comment]
Hi @danzen, 

It works well. Thank you so much.
