### ISSUE TITLE
Where is library repository?

### ISSUE THREAD

**Issue by luckylooke** [danzen/zimjs#48]
Where is source code of the library? I suppose that https://github.com/danzen/zimjs/blob/master/zim.js is product of som dev ops. Please don't tell me that it is a source... all in one file 80000 lines.
And also, is there some overview architecture described somewhere?
Thanks 🙏

**Comment by danzen** [comment]
Hi @luckylooke - yes, that is the source.  There is some information at the start of the file about architecture and reasoning.  There are the docs at https://zimjs.com/docs.html that are drawn from the source.  And you are welcome to come discuss at https://zimjs.com/slack or https://zimjs.com/discord.  We welcome thoughts!  Cheers.
