### ISSUE TITLE
access to plasma zapp not working

### ISSUE THREAD

**Issue by xavax31** [danzen/zimjs#52]
I click to 'login to start', log in, and I stay blocked to the page 'you're currently logged as' (cf screenshot). Tried on mac/chrome and iphone/safari, same problem.
<img width="965" alt="Capture d’écran 2023-07-06 à 11 59 50" src="https://github.com/danzen/zimjs/assets/4051022/0196f883-8408-4a3d-a537-c48f2e9b6134">

**Comment by danzen** [comment]
That is a tab so close it with the Done < at the top (or x in android) and you will be in the app again.  If you do not see a close button, please re-open the issue.  We see one.  Cheers.
