### ISSUE TITLE
ZIM NPM, Vue, Svelte, React and Angular

### ISSUE THREAD

**Issue by danzen** [danzen/zimjs#53]
We have now updated our NPM to be more robust.  

https://www.npmjs.com/package/zimjs

There is now a repo of templates for Vue, Svelte, React and Angular here 

https://github.com/yoanhg421/zimjs-templates

Thanks @yoanhg421 for working through all this with us - as well as to those in the past for imput.  It has been an ongoing issue for devs for some time.  We did have solutions but they were work-arounds.  Now importing and requiring ZIM should work as expected.

**Comment by danzen** [comment]
And all the helper modules are available now too https://zimjs.com/code.html#npm

**Comment by jikkuatwork** [comment]
Can Zim be used without npm or libraries? I wish to use with vanilla js & via a CDN module. Is it possible?

**Comment by danzen** [comment]
Sorry for the delay, @jikkuatwork - yes - we use ZIM all the time on its own via CDN - that is what all the examples are on the ZIM site at https://zimjs.com and EXAMPLES.  See the CODE page for for the template which uses the CDN.

You are welcome to join us at https://forum.zimjs.com or https://zimjs.com/discord
