### ISSUE TITLE
CPU usage on web docs

### ISSUE THREAD

**Issue by deltaGPhys** [danzen/zimjs#56]
This is really odd, but... My MB Pro (Intel), using the latest Chrome, sees huge (>500%) CPU usage when viewing the docs (https://zimjs.com/docs.html?items=Tabs,Pad). It looks like it's actually the spiral widget that causes it. When I pull the little control down all the way to stop it, CPU usage returns to normal. It seems to be an issue with that widget specifically; when I use the online editor with my own code or the orb game, the issue doesn't happen; it's only when viewing the docs. In the screenshot, it's really clear when it was running.

<img width="216" alt="Screen Shot 2024-09-06 at 11 45 32 PM" src="https://github.com/user-attachments/assets/c2ba56ea-3f16-4d21-be5e-af019b572218">

**Comment by danzen** [comment]
Strange.  I mean, the docs is a pretty large page - but we have been running it for 10 years and never had any problems or reports.
