### ISSUE TITLE
Rewind fails in fast animation

### ISSUE THREAD

**Issue by markphd** [danzen/zimjs#6]
Continuing the issue I raised from [Youtube](https://www.youtube.com/watch?v=BGilBP2D0-Y&index=12&list=PLCIzupgRt1pa0ms72BZzoAeJkLazlWeFJ), 

> If the double click time is under a 300 ms then the protect aspect of the loop or rewind is not activated yet.

**Comment by danzen** [comment]
Hi Mark - the new version of ZIM 4.9.0 fixes that issue you found. Thanks again for letting us know. The glitch was introduced when we added animation series - we needed to wait until the whole series was assigned before protecting loop and rewind animations. So we put in a short delay. The solution to stop a fast doubleclick before the protect was assigned was to set the target mouseenabled to false and then set it back again after the 70ms delay. There might have been another way - but animation series are quite complex so this seemed the most solid solution.
