### ISSUE TITLE
I wonder if this is doable in Zim

### ISSUE THREAD

**Issue by markphd** [danzen/zimjs#7]
I found this in Chrome experiment projects, I think it involves a lot of Math in here but no worries, I can learn little by little, however I would like to ask if this can be done in Zim.js? 

Codepen: http://codepen.io/markphd/pen/PpKvMm
Original source: http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage

**Comment by danzen** [comment]
Hi Mark - sorry for the delay - missed that your post was here.  That is a cool effect.  Was just doing some work on a particle emitter that has a similar feel.  http://zimjs.com/code/particles/  I expect that it can be done in ZIM as it lets you render dynamic images like other other canvas libraries.

**Comment by markphd** [comment]
Thanks @danzen - this is awesome! 👍

**Comment by wiggleMyEars** [comment]
Hi Dan,
Loving your library! I have a 'I wonder if this is doable in Zen' request too. Is it possible with Zim.Frame to toggle between 'tagID' and 'Fit', i.e. to toggle full screen?
Thanks again for this great library.
James

**Comment by danzen** [comment]
Hi James - sorry, missed this one down here.  Maybe I should just leave this thread here as it can apply to many things! ;-)  That is a good idea to be able to do that - let me experiment...

**Comment by danzen** [comment]
http://zimjs.com/code/expand/ works pretty well.  There are two frames and we put the content in a Container called shell.  Then move the shell from one stage to the other.  We hide and show the different html tags accordingly.

**Comment by wiggleMyEars** [comment]
Wow! Thank you that's totally brilliant! 
Loving your library,
James
