### ISSUE TITLE
Guide and Grid: ReferenceError: addedInterval is not defined

### ISSUE THREAD

**Issue by malus** [danzen/zimjs#9]
Hi Danzen!
I see in the code 
`clearInterval(addedInterval);`
but addedInterval is never defined.

Bye

**Comment by danzen** [comment]
Thanks Fabio - when we updated the Grid and Guide to use the zim.added() we forgot to assign the return value to the var addedInterval!  Will fix in 5.2.0 launching tomorrow (today) once we get some sleep!

**Comment by danzen** [comment]
Hi Fabio - there is a version 5.2.0 that will fix this issue: https://d309knd7es5f10.cloudfront.net/zim_5.2.0.js We have not quite launched it as we are checking on some StageGL features - but that will not affect you - and it is live at the moment with live docs.  Thanks again and let us know if you find anything else.

**Comment by malus** [comment]
Thank you Dan. Now it's ok!
I currently develop with your great creation!!! I will inform you if I find something...
bye
